Отображение задач
Rema04Dev/todoist pull request #2
Opened 2023-08-29 08:13 UTC by Rema04Dev

2023-08-29 09:24 UTC, fixmylie requested changes

2023-08-29 09:24 UTC, fixmylie commented on src/components/TodoList.tsx
> +export const TodoList = (props: TodoListProps) => {
нужно обернуть в observer иначе рендера происходить не будет

2023-08-29 09:24 UTC, fixmylie commented on src/store/todosStore.ts
> +export default new TodosStore();
почитать по поводу синглтона https://mobx-cookbook.github.io/react-integration/singleton

2023-08-29 12:19 UTC, Rema04Dev commented on src/components/TodoList.tsx
> +export const TodoList = (props: TodoListProps) => {
Сделал. Убрал observer из <App />, теперь данные получаю напрямую в <TodoList />

2023-08-30 06:34 UTC, fixmylie commented on src/store/todosStore.ts
> +export default new TodosStore();
Все верно. Это тебе для ознакомления какие способы еще бывают про их плюсы и минусы

2023-08-30 06:35 UTC, fixmylie commented on src/store/todosStore.ts
> +export default new TodosStore();
Буду более корректно и емко мысль формулировать, чтобы догадки не строить к чему я это. Разучился немного х)

2023-08-31 07:37 UTC, fixmylie requested changes

2023-08-31 07:37 UTC, fixmylie commented on .editorconfig
> +root = true
Проверка

2023-08-31 07:40 UTC, fixmylie approved these changes

2023-08-31 07:40 UTC, fixmylie commented on .editorconfig
> +root = true
Окей

2023-08-31 07:41 UTC, fixmylie approved these changes

2023-08-31 07:41 UTC, fixmylie commented on .editorconfig
> +end_of_line = lf
фыав

2023-08-31 07:51 UTC, merged